/**

SEO Product Description Generator.

This tool works by allowing the AI (which is excellent at creative writing) to "save" its creative output directly back into NetSuite.

Workflow:

You ask: "Write a punchy, SEO-optimized description for the 'Hiking Backpack 3000' focusing on durability."

AI generates: "Conquer any trail with the Hiking Backpack 3000..."

AI calls this tool: To save that text into the "Web Store Description" field of the item.

1. SuiteScript 2.1 Logic File (SeoUpdateTool.js)
This script updates the customer-facing web fields on the Inventory Item record.

 */


/**
 * @NApiVersion 2.1
 * @NScriptType CustomTool
 */
define(['N/record', 'N/search', 'N/log'], (record, search, log) => {

    /**
     * Updates the Web Store Description and Page Title for an Item.
     * * @param {Object} params - Input parameters from the AI.
     * @param {string} params.itemSKU - The exact SKU/Name of the item.
     * @param {string} params.seoDescription - The long-form HTML or text description generated by AI.
     * @param {string} params.pageTitle - (Optional) A short, catchy title for the browser tab.
     * @returns {Object} Result object indicating success.
     */
    const updateItemSEO = (params) => {
        try {
            log.audit({ title: 'SEO Tool Invocation', details: `Updating SKU: ${params.itemSKU}` });

            // Step 1: Find Item Internal ID
            const itemId = getItemId(params.itemSKU);
            
            if (!itemId) {
                return { 
                    success: false, 
                    message: `Item SKU '${params.itemSKU}' not found.` 
                };
            }

            // Step 2: Load the Inventory Item
            // Note: If you have Assembly Items or Kits, you might need dynamic logic here.
            // For simplicity, we assume Inventory Item.
            const itemRec = record.load({
                type: record.Type.INVENTORY_ITEM,
                id: itemId,
                isDynamic: true
            });

            // Step 3: Update Fields
            // 'storedescription' is the "Detailed Description" shown on the web store.
            if (params.seoDescription) {
                itemRec.setValue({ fieldId: 'storedescription', value: params.seoDescription });
            }

            // 'pagetitle' is the HTML <title> tag for SEO.
            if (params.pageTitle) {
                itemRec.setValue({ fieldId: 'pagetitle', value: params.pageTitle });
            }

            // Step 4: Save
            const id = itemRec.save();

            return {
                success: true,
                itemId: id,
                itemSKU: params.itemSKU,
                message: `Successfully updated SEO content for ${params.itemSKU}.`
            };

        } catch (e) {
            log.error({ title: 'SEO Tool Failure', details: e });
            return { success: false, message: e.message };
        }
    };

    // Helper: Find Item ID by Name
    const getItemId = (sku) => {
        const s = search.create({
            type: search.Type.ITEM,
            filters: [['itemid', 'is', sku]],
            columns: ['internalid']
        });
        const res = s.run().getRange({ start: 0, end: 1 });
        return res.length ? res[0].getValue('internalid') : null;
    };

    return {
        updateItemSEO: updateItemSEO
    };
});



/**
2. Tool Definition Schema (SeoUpdateSchema.json)
This schema tells the AI that once it has written a great description, it should use this tool to publish it.

{
  "name": "updateItemSEO",
  "description": "Publishes a new product description and page title to the NetSuite Web Store. Use this tool AFTER generating creative content for an item.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "itemSKU": {
        "type": "string",
        "description": "The exact SKU or Item Name as it appears in NetSuite."
      },
      "seoDescription": {
        "type": "string",
        "description": "The full, creative product description text (HTML is allowed) to be displayed on the website."
      },
      "pageTitle": {
        "type": "string",
        "description": "A short, SEO-optimized title for the browser tab (max 60 chars)."
      }
    },
    "required": ["itemSKU", "seoDescription"],
    "nullable": ["pageTitle"]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "success": { "type": "boolean" },
      "itemId": { "type": "string" },
      "message": { "type": "string" }
    }
  }
}

 */



/**
  
3. SDF Object XML (customtool_seo_generator.xml)
This XML ensures the tool has permission to edit Items, specifically the web store fields.


<tool scriptid="customtool_seo_generator">
    <name>SEO Content Publisher</name>
    <description>Allows AI to update item descriptions and page titles.</description>
    <scriptfile>[/SuiteScripts/AI_Tools/SeoUpdateTool.js]</scriptfile>
    <schemafile>[/SuiteScripts/AI_Tools/SeoUpdateSchema.json]</schemafile>
    <exposeto3rdpartyagents>T</exposeto3rdpartyagents>
    <permissions>
        <permission>
            <permkey>LIST_ITEM</permkey>
            <permlevel>EDIT</permlevel>
        </permission>
    </permissions>
</tool>

 */




/**

How to Test This :

Deploy: Upload the files and create the Custom Tool record.

Prompt the AI:

"Find the item 'Blue Cotton Shirt'. Write a 3-sentence exciting description for it that mentions it's made of Egyptian cotton. Then, save this description to the item record."

Result:

The AI will first generate the text (e.g., "Experience the luxury of 100% Egyptian cotton...").

It will then call your tool, passing "Blue Cotton Shirt" and that text string.

Go to the Item Record > Web Store subtab to verify the Detailed Description field has been updated.

 */