/**
 
"Universal Answer" tool to include a "Persistence Layer."

Since SuiteQL results are raw data (not a native "Saved Search" object), the best way to "save" this report is to have the tool automatically generate a CSV or Excel file and store it in your NetSuite File Cabinet.

Here is the upgraded Text-to-SuiteQL Reporter that can either give a quick answer OR save a file.

1. SuiteScript 2.1 Logic File (SuiteQLReporterTool.js)
This script has two modes:

Preview Mode: Returns the first 20 rows so the AI can answer the user immediately.

Save Mode: Fetches up to 1,000 rows, converts the data to a CSV file, saves it to the File Cabinet, and returns the download link.

 */



/**
 * @NApiVersion 2.1
 * @NScriptType CustomTool
 */
define(['N/query', 'N/file', 'N/log'], (query, file, log) => {

    /**
     * Executes a SuiteQL Query and optionally saves the result as a CSV file.
     * @param {Object} params - Input parameters from the AI.
     * @param {string} params.sqlQuery - The actual SuiteQL string generated by the AI.
     * @param {boolean} params.saveToFile - If true, saves a CSV in File Cabinet. If false, returns JSON text.
     * @param {string} params.fileName - (Optional) Name of the report file (e.g. "Sales_Report_Q1.csv").
     * @returns {Object} Result object with data or file link.
     */
    const runSuiteQL = (params) => {
        try {
            log.audit({ title: 'SuiteQL Tool', details: `Saving? ${params.saveToFile} | Query: ${params.sqlQuery}` });

            // 1. Run the Query
            // We use paged run to handle potential large datasets safely
            const myQuery = query.runSuiteQL({ query: params.sqlQuery });
            const results = myQuery.results;

            if (results.length === 0) {
                return { success: true, message: "Query executed successfully but returned no results." };
            }

            // MODE A: Quick Answer (No Save)
            if (!params.saveToFile) {
                // Return top 20 rows for the Chatbot to read
                return {
                    success: true,
                    dataPreview: results.slice(0, 20), 
                    totalRows: results.length,
                    message: "Here is a preview of the data. Ask me to 'save this report' to get the full file."
                };
            }

            // MODE B: Save to File Cabinet
            if (params.saveToFile) {
                
                // 1. Convert JSON results to CSV string
                const headers = Object.keys(results[0]).join(',');
                const rows = results.map(row => {
                    return Object.values(row).map(val => {
                        // Sanitize value: escape quotes and wrap in quotes if it contains commas
                        if (val === null || val === undefined) return '';
                        const str = String(val);
                        if (str.includes(',') || str.includes('"')) {
                            return `"${str.replace(/"/g, '""')}"`;
                        }
                        return str;
                    }).join(',');
                }).join('\n');

                const csvContent = `${headers}\n${rows}`;

                // 2. Create File
                // Target Folder: Use ID -15 (SuiteScripts) for test, or replace with a dedicated "Reports" folder ID.
                const reportFile = file.create({
                    name: params.fileName || `AdHoc_Report_${Date.now()}.csv`,
                    fileType: file.Type.CSV,
                    contents: csvContent,
                    folder: -15 
                });

                const fileId = reportFile.save();

                // 3. Generate URL (Dynamic path)
                const fileObj = file.load({ id: fileId });
                
                return {
                    success: true,
                    savedToFile: true,
                    fileId: fileId,
                    fileName: fileObj.name,
                    downloadUrl: fileObj.url,
                    message: `Report saved successfully. File ID: ${fileId}.`
                };
            }

        } catch (e) {
            log.error({ title: 'SuiteQL Failure', details: e });
            return { success: false, message: `SQL Error: ${e.message}` };
        }
    };

    return {
        runSuiteQL: runSuiteQL
    };
});




/**
 
2. Tool Definition Schema (SuiteQLReporterSchema.json)
This schema instructs the AI to write the SQL itself, and then decide whether to just peek at the data or save it based on the user's request.

 */

{
  "name": "runSuiteQL",
  "description": "Executes a SuiteQL (SQL) query against the NetSuite database. Can returns raw data OR save the results as a CSV file.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "sqlQuery": {
        "type": "string",
        "description": "The valid SuiteQL query string (e.g. 'SELECT id, entityid FROM customer')."
      },
      "saveToFile": {
        "type": "boolean",
        "description": "Set to TRUE if the user asks to 'save', 'download', or 'export' the report. Set to FALSE for quick answers."
      },
      "fileName": {
        "type": "string",
        "description": "The desired name of the file if saving (e.g. 'Customer_List_CA.csv')."
      }
    },
    "required": ["sqlQuery", "saveToFile"],
    "nullable": ["fileName"]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "success": { "type": "boolean" },
      "dataPreview": { "type": "array" },
      "fileId": { "type": "number" },
      "downloadUrl": { "type": "string" },
      "message": { "type": "string" }
    }
  }
}



/**

3. SDF Object XML (customtool_suiteql_reporter.xml)
We need to add permission to create documents (DOC_DOCUMENTS) so the script can save the CSV file.

 */


<tool scriptid="customtool_suiteql_reporter">
    <name>Universal SuiteQL Reporter</name>
    <description>Runs SQL queries and saves results to File Cabinet.</description>
    <scriptfile>[/SuiteScripts/AI_Tools/SuiteQLReporterTool.js]</scriptfile>
    <schemafile>[/SuiteScripts/AI_Tools/SuiteQLReporterSchema.json]</schemafile>
    <exposeto3rdpartyagents>T</exposeto3rdpartyagents>
    <permissions>
        <permission>
            <permkey>DOC_DOCUMENTS</permkey>
            <permlevel>CREATE</permlevel>
        </permission>
        <permission>
            <permkey>LIST_FIND</permkey>
            <permlevel>VIEW</permlevel>
        </permission>
    </permissions>
</tool>



/**
 
How to Test This:

Scenario 1: The Quick Ask

User: "How many customers do we have in California?"

AI: Generates SQL SELECT Count(id) FROM Customer WHERE billstate = 'CA'.

Tool: Runs with saveToFile: false.

Result: AI replies: "You have 45 customers in California."

Scenario 2: The Report Generation

User: "Okay, create a report of all those California customers, including their email and phone number, and save it for me."

AI: Generates SQL SELECT entityid, email, phone FROM Customer WHERE billstate = 'CA'.

Tool: Runs with saveToFile: true and fileName: "California_Customers.csv".

Result: The script generates the CSV, puts it in the File Cabinet, and the AI replies: "I have saved the report 'California_Customers.csv' to your File Cabinet. You can download it here: [Link]"
 */